### ISSUE TITLE
Compiler and program output aren't HTML-escaped

### ISSUE THREAD

**Issue by sschwarzer** [PMunch/nim-playground-frontend#1]
Copied from https://github.com/zacharycarter/nim-playground/issues/4 :

For example, if you enter the snippet
```
echo "<b>foo</b>"
```
"foo" is displayed in bold.

For the compiler output it's also quite inconvenient because error messages that include a `<Type>` in angle brackets are seen as invalid tags by the browser and aren't displayed.

**Comment by PMunch** [comment]
Ah yes, this is a known issue. I am currently redoing that part of the code, moving the ANSI -> HTML colourisation from the front-end to the server. But since I couldn't find any ANSI -> HTML libraries I have to write that first. Once that's in place the output from the compiler should first be HTML escaped, then colourised, then passed to the front-end for direct display.

**Comment by PMunch** [comment]
This has now been done, and the playground now escapes HTML and uses the ANSI colour to colourise the output.
